In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
#load the XLS file as a Pandas DataFrame and preview the DataFrame:
df_table = pd.read_csv(r'C:\Users\Sergio_Paramo\Documents\Projects\Domino\DomnoBaseline\Ph_1_downloads\T_ITEM_102721.csv', low_memory=False)
df_table

,000007,MOL-A OFFICE 2000 WIN32 VLIC ENGL,MOL-A OFFICE 2000 WIN32 VLIC ENGLISH/MULTILANG UN-2,P,,B,15000,DW300,MOL-A OFFICE 2000 WIN32,0.010,...,0.7,0.8,3023151,NULL.22,NULL.23,NULL.24,NULL.25,0.9,NULL.26,NULL.27
0,000015,MOL-A UPG PREV VER/1 MSAPP V,MOL-A Upg Prev Ver/1 MSAPP VLic Office 2000...,P,,B,15000,DW115,MOL-A UPG PREV VER/1 MSAPP V,0.01,...,0,0,3023328,NaN,NaN,NaN,NaN,0,NaN,NaN
1,000017,MOL-B UPG PREV VER/1 MSAPP V,MOL-B Upg Prev Ver/1 MSAPP VLic Office 2000...,P,,B,15000,DW115,MOL-B UPG PREV VER/1 MSAPP V,0.01,...,0,0,3023417,NaN,NaN,NaN,NaN,0,NaN,NaN
2,000019,MOL-C UPG PREV VER/1 MSAPP VLIC OFFICE,MOL-C Upg Prev Ver/1 MSAPP VLic Office 2000 ...,P,NaN,B,17000,DW117,NaN,0.01,...,0,0,3023619,NaN,NaN,NaN,NaN,0,NaN,NaN
3,000042,RUNNING MS WINDOWS 2000 BOOK PROFESSI,Running MS WINDOWS 2000 Book Professional ...,P,,B,15000,DW169,NaN,55.00,...,0,0,3024061,NaN,NaN,NaN,NaN,0,NaN,NaN
4,000044,INTELLIMOUSE OPTICAL PS2 USB CROM ENGL,INTELLIMOUSE OPTICAL PS2 USB CROM ENGLISH NA H...,P,,B,41000,DW90,INTELLIMOUSE OPTICAL PS2/USB,0.70,...,0,0,3024195,NaN,NaN,NaN,NaN,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9468085,YYYV5,"ASSY,LCD,WWAN,STCH-B,M11XR2","Assembly,Liquid Crystal Display,Wireless Wide ...",A,,C,MO100,NaN,NaN,3.00,...,0,0,8056007,NaN,NaN,NaN,NaN,0,NaN,NaN
9468086,YYYWV,"SI,MOD,INFO,BIOS,FRZ,E4310,A07","System Integration,Module,Information,BIOS,Fre...",A,,6,SI000,NaN,NaN,0.00,...,0,0,2072404,NaN,NaN,NaN,NaN,0,NaN,NaN
9468087,YYYX1,FGA Proxy MODYYYX1for SKU 998-DVOM,FGA Proxy MODYYYX1for SKU 998-DVOM,A,55,R,ZA000,NaN,NaN,0.00,...,0,0,12828294,NaN,NaN,NaN,NaN,0,NaN,NaN
9468088,YYYY8,"ASSY,FAN,REV-AIR,S55","Assembly,Fan,REV-AIR,S55",A,,C,AC000,NaN,NaN,0.50,...,0,0,8056025,NaN,NaN,NaN,NaN,0,NaN,NaN
9468089,YYYYC,"ASSY,CBL,NVME,C7,16+8X2.5,R750","ASSY,CBL,NVME,C7,16+8X2.5,R750",A,,C,CA000,NaN,Canada price is $40.99,0.50,...,0,0,14335439,NaN,NaN,NaN,NaN,0,NaN,NaN

Total number of rows

In [7]:
rows = len(df_table)
rows

9468090

In [8]:
# Check table data types 
data_type = pd.DataFrame(
    df_table.dtypes,
    columns=['Data Type']
)

In [9]:
# Check missing data
missing_data = pd.DataFrame(
    df_table.isnull().sum(), 
    columns=['Missing Values']
)

missing_data

                                                    Missing Values
000007                                                           0
MOL-A OFFICE 2000 WIN32        VLIC ENGL                        30
MOL-A OFFICE 2000 WIN32        VLIC ENGLISH/MUL...             308
P                                                               88
                                                           5355670
...                                                            ...
NULL.24                                                    9468076
NULL.25                                                    9468084
0.9                                                              0
NULL.26                                                    9441716
NULL.27                                                    9468087

[62 rows x 1 columns]

In [10]:
# Unique value check
unique_values = pd.DataFrame(
    columns=['Unique Values']
)
for row in list(df_table.columns.values):
    unique_values.loc[row] = [df_table[row].nunique()]

In [11]:
# Column Compleness % 
comp = pd.DataFrame(
    columns=['% Complete']
)
for row in list(df_table.columns.values):
    comp.loc[row] = [df_table[row].nunique()*100/rows]    
comp

                                                    % Complete
000007                                              100.000000
MOL-A OFFICE 2000 WIN32        VLIC ENGL             44.766907
MOL-A OFFICE 2000 WIN32        VLIC ENGLISH/MUL...   50.261785
P                                                     0.000063
                                                      0.000549
...                                                        ...
NULL.24                                               0.000106
NULL.25                                               0.000063
0.9                                                   0.000021
NULL.26                                               0.039755
NULL.27                                               0.000032

[62 rows x 1 columns]

In [12]:
# # Min and Max Values
# maximum_values = pd.DataFrame(
#     columns=['Maximum Value']
# 
# for row in list(df_table.columns.values):
#     maximum_values.loc[row] = [df_table[row].max()]

In [13]:
dq_report = data_type.join(missing_data).join(unique_values).join(comp)
dq_report

,Data Type,Missing Values,Unique Values,% Complete
000007,object,0,9468090,100.000000
MOL-A OFFICE 2000 WIN32 VLIC ENGL,object,30,4238571,44.766907
MOL-A OFFICE 2000 WIN32 VLIC ENGLISH/MULTILANG UN-2,object,308,4758831,50.261785
P,object,88,6,0.000063
,object,5355670,52,0.000549
...,...,...,...,...
NULL.24,float64,9468076,10,0.000106
NULL.25,object,9468084,6,0.000063
0.9,int64,0,2,0.000021
NULL.26,object,9441716,3764,0.039755
NULL.27,object,9468087,3,0.000032